# .air.toml
root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  full_bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  watch_dir = ["."]
  exclude_regex = ["_test\\.go"]

[log]
  level = "debug"

[events]
  before_build = "echo 'Before build...'"
  after_build = "echo 'After build...'"

