version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - setup_remote_docker:
          version: 20.10.7

      - checkout

      - run:
          name: Install Docker Compose
          command: |
            curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose
            chmod +x docker-compose
            sudo mv docker-compose /usr/local/bin/docker-compose

      - run:
          name: Verify Docker Compose Installation
          command: docker-compose --version

      - run:
          name: Build and Run Services
          command: docker-compose -f ../docker-compose.yml up --build -d

      - run:
          name: Run Tests
          command: docker-compose exec frontend npm run test

      - run:
          name: Stop and Cleanup
          command: docker-compose down

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
